import { config } from "./schema-generation-config";
import type { TableToGenerate } from "./table-parser";

const header = `
// This file is generated by the generate-schema.ts script.
// Do not edit this file manually.

import { z } from "zod";
`.trim();

const schemaHeader = () =>
  `
export const ${config().schemaExportName} = {
`.trim();

const footer = () =>
  `
};

type Schemas = typeof ${config().schemaExportName};
type RowTypes = {
  [K in keyof Schemas]: Schemas[K]["types"] & {
    notNull: Schemas[K]["notNullTypes"];
  };
};

export const rowTypes: RowTypes = Object.fromEntries(
  Object.entries(${config().schemaExportName}).map(([key, value]) => [
    key,
    { ...value.types, notNull: value.notNullTypes },
  ]),
) as unknown as RowTypes;
`.trim();

const generateTableSchema = (table: TableToGenerate) => {
  const transformedTableName = config().tableNameTransform(table.name);
  return `
  ${transformedTableName}: {
    tableName: "${table.name}",
    types: {
      ${table.columns.map((column) => `${config().columnNameTransform(column.name)}:  ${column.isPrimaryKey ? `${transformedTableName}${config().primaryKeySuffix}Schema` : column.zodType},`).join("\n")}
    },
    notNullTypes: {
      ${table.columns.map((column) => `${config().columnNameTransform(column.name)}: ${column.isPrimaryKey ? `${transformedTableName}${config().primaryKeySuffix}Schema` : column.zodTypeWithoutNullable},`).join("\n")}
    },
    validator: z.object({
      ${table.columns.map((column) => `${config().columnNameTransform(column.name)}: ${column.isPrimaryKey ? `${transformedTableName}${config().primaryKeySuffix}Schema` : column.zodTypeWithoutNullable},`).join("\n")}
    }).strict(),
    notNullValidator: z.object({
      ${table.columns.map((column) => `${config().columnNameTransform(column.name)}: ${column.isPrimaryKey ? `${transformedTableName}${config().primaryKeySuffix}Schema` : column.zodTypeWithoutNullable},`).join("\n")}
    }).strict(),
  },
  `.trim();
};

const generateRowTypeExports = (tables: TableToGenerate[]) => {
  return `
  ${tables
    .map((table) => {
      const transformedTableName = config().tableNameTransform(table.name);
      return `export const ${transformedTableName} = rowTypes.${transformedTableName};`;
    })
    .join("\n")}
  `.trim();
};

const generateTableId = (table: TableToGenerate) => {
  const idColumn = table.columns.find(
    (column) => column.name === `${table.name}_id`,
  );
  if (!idColumn) {
    return "";
  }

  const transformedTableName = config().tableNameTransform(table.name);
  return `
  export const ${transformedTableName}${config().primaryKeySuffix}Schema = ${idColumn.zodTypeWithoutNullable}.brand<"${transformedTableName}${config().primaryKeySuffix}">();
  export type ${transformedTableName}${config().primaryKeySuffix} = z.infer<typeof ${transformedTableName}${config().primaryKeySuffix}Schema>;
  `;
};

const generateTableTypeExport = (table: TableToGenerate) => {
  const transformedTableName = config().tableNameTransform(table.name);
  return `
  export type ${transformedTableName}${config().tableTypeSuffix} = z.infer<typeof ${config().schemaExportName}.${transformedTableName}.validator>;
  export type ${transformedTableName}${config().tableTypeSuffix}NotNull = z.infer<typeof ${config().schemaExportName}.${transformedTableName}.notNullValidator>;
  `;
};

export const generateSchemaTypescript = (tables: TableToGenerate[]) => {
  return `
  ${header}
  ${tables.map((table) => generateTableId(table)).join("\n")}
  ${schemaHeader()}
  ${tables.map((table) => generateTableSchema(table)).join("\n")}
  ${footer()}

  ${tables.map((table) => generateTableTypeExport(table)).join("\n")}

  ${generateRowTypeExports(tables)}

  `.trim();
};
